# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-30 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessname', models.CharField(max_length=100)),
                ('businesstype', models.CharField(max_length=100)),
                ('aadhaarOwner', models.CharField(max_length=100)),
                ('businessaddress', models.CharField(max_length=100)),
                ('businessId', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('required', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'business_table_model',
            },
        ),
        migrations.CreateModel(
            name='EKYCBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessId', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'ekyc_table',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(max_length=100)),
                ('datacreater', models.CharField(max_length=500)),
                ('datajoiner', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'session_table',
            },
        ),
    ]
